# Generated by Django 5.2.4 on 2025-07-15 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_ID', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('chat', models.CharField(max_length=100)),
                ('work_phone', models.CharField(max_length=20)),
                ('buisness_address', models.CharField(max_length=255)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('manager_ID', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100)),
                ('P_description', models.TextField()),
                ('P_state', models.CharField(max_length=50)),
                ('p_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_budgeted', models.BooleanField()),
                ('progress', models.IntegerField()),
                ('priority', models.CharField(max_length=50)),
                ('requestor', models.CharField(max_length=100)),
                ('digital_starategy', models.CharField(max_length=255)),
                ('digitalization', models.BooleanField()),
                ('p_start_date', models.DateField()),
                ('p_end_date', models.DateField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_ID', models.AutoField(primary_key=True, serialize=False)),
                ('requestType', models.CharField(max_length=100)),
                ('Driver', models.CharField(max_length=100)),
                ('objective', models.TextField()),
                ('Scope', models.TextField()),
                ('Requirments', models.TextField()),
                ('request_state', models.CharField(max_length=100)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('stages_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stage_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('s_start_date', models.DateField()),
                ('s_end_date', models.DateField()),
                ('s_progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('File_ID', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='project',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.request'),
        ),
        migrations.AddField(
            model_name='stages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stages'),
        ),
    ]
