# Generated by Django 5.2.4 on 2025-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=255)),
                ('P_description', models.TextField()),
                ('P_state', models.CharField(max_length=50)),
                ('p_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('p_budgeted', models.BooleanField()),
                ('progress', models.IntegerField()),
                ('priority', models.CharField(max_length=50)),
                ('requestor', models.CharField(max_length=255)),
                ('digital_starategy', models.CharField(max_length=255)),
                ('digitalization', models.BooleanField()),
                ('p_start_date', models.DateField()),
                ('p_end_date', models.DateField()),
                ('request_ID', models.IntegerField()),
                ('dep_ID', models.IntegerField()),
            ],
            options={
                'db_table': 'users_project',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='manages',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
        migrations.RemoveField(
            model_name='manages',
            name='Emp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='request',
        ),
        migrations.RemoveField(
            model_name='stages',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manages',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
