# Generated by Django 5.2.4 on 2025-07-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userproject_remove_manages_dep_remove_project_dep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
    ]
