# Generated by Django 5.2.4 on 2025-07-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_request_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_ID',
            new_name='Request_ID',
        ),
        migrations.RemoveField(
            model_name='request',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='request',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requestType',
        ),
        migrations.AddField(
            model_name='request',
            name='Drive',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='Project_Title',
            field=models.CharField(default='Untitled Project', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='Request_Type',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='dep_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='Requirments',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='request',
            name='Scope',
            field=models.CharField(default='General Scope', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_state',
            field=models.CharField(default='waiting', max_length=50),
        ),
        migrations.AlterModelTable(
            name='request',
            table='users_request',
        ),
        migrations.AddField(
            model_name='request',
            name='Objective',
            field=models.TextField(default='No Objective'),
        ),
    ]
