# Generated by Django 5.2.4 on 2025-07-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_request_id_request_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Drive',
            new_name='Driver',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Request_Type',
            new_name='requestType',
        ),
    ]
