# Generated by Django 5.2.4 on 2025-07-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_drive_request_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dep_name', models.CharField(db_column='Dep_name', max_length=255, primary_key=True, serialize=False)),
                ('Location', models.CharField(blank=True, db_column='Location', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('PRN', models.AutoField(db_column='PRN', primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(db_column='Emp_name', max_length=255)),
                ('Job_title', models.CharField(blank=True, db_column='Job_title', max_length=255)),
                ('Email', models.EmailField(blank=True, db_column='Email', max_length=254)),
                ('Chat', models.CharField(blank=True, db_column='Chat', max_length=255)),
                ('Work_phone', models.CharField(blank=True, db_column='Work_phone', max_length=50)),
                ('Buisness_address', models.CharField(blank=True, db_column='Buisness_address', max_length=255)),
                ('Employee_count', models.IntegerField(db_column='Employee_count', default=1)),
                ('Grade', models.CharField(blank=True, db_column='Grade', max_length=50)),
                ('Emp_role', models.CharField(db_column='Emp_role', max_length=50)),
                ('Dep_name', models.ForeignKey(blank=True, db_column='Dep_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('P_ID', models.AutoField(db_column='P_ID', primary_key=True, serialize=False)),
                ('Project_title', models.CharField(db_column='Project_title', max_length=255)),
                ('Request_type', models.CharField(db_column='Request_type', max_length=100)),
                ('Drive', models.CharField(db_column='Drive', max_length=255)),
                ('Objective', models.TextField(db_column='Objective')),
                ('type', models.TextField(db_column='type')),
                ('Scope', models.TextField(db_column='Scope')),
                ('Priority', models.CharField(db_column='Priority', max_length=100)),
                ('Regulatory', models.CharField(blank=True, db_column='Regulatory', max_length=100, null=True)),
                ('Requirements', models.TextField(db_column='Requirements')),
                ('Request_state', models.CharField(db_column='Request_state', max_length=100)),
                ('Forwarded', models.BooleanField(db_column='Forwarded')),
                ('Approved', models.BooleanField(db_column='Approved')),
                ('Assigned', models.BooleanField(db_column='Assigned')),
                ('P_description', models.TextField(db_column='P_description')),
                ('P_state', models.CharField(db_column='P_state', max_length=100)),
                ('P_budget', models.DecimalField(db_column='P_budget', decimal_places=2, max_digits=15)),
                ('P_budgeted', models.BooleanField(db_column='P_budgeted')),
                ('Progress', models.IntegerField(db_column='Progress')),
                ('Requestor', models.CharField(db_column='Requestor', max_length=255)),
                ('Digital_strategy', models.TextField(db_column='Digital_strategy')),
                ('Digitalization', models.BooleanField(db_column='Digitalization')),
                ('P_start_date', models.DateField(db_column='P_start_date')),
                ('P_end_date', models.DateField(db_column='P_end_date')),
                ('Dep_name', models.ForeignKey(blank=True, db_column='Dep_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('PRN', models.ForeignKey(blank=True, db_column='PRN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('Stages_ID', models.AutoField(db_column='Stages_ID', primary_key=True, serialize=False)),
                ('Stage_name', models.CharField(db_column='Stage_name', max_length=100)),
                ('Status', models.CharField(db_column='Status', max_length=100)),
                ('S_start_date', models.DateField(db_column='S_start_date')),
                ('S_end_date', models.DateField(db_column='S_end_date')),
                ('S_progress', models.IntegerField(db_column='S_progress')),
                ('P_ID', models.ForeignKey(db_column='P_ID', on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_ID', models.AutoField(db_column='Task_ID', primary_key=True, serialize=False)),
                ('Task_name', models.CharField(db_column='Task_name', max_length=100)),
                ('File', models.FileField(blank=True, db_column='File', null=True, upload_to='tasks/')),
                ('Stages_ID', models.ForeignKey(db_column='Stages_ID', on_delete=django.db.models.deletion.CASCADE, to='users.stages')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
        migrations.AddField(
            model_name='employee',
            name='P_ID',
            field=models.ForeignKey(blank=True, db_column='P_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.project'),
        ),
    ]
