# Generated by Django 5.2.4 on 2025-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_employee_project_stages_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Request_state',
        ),
        migrations.AlterField(
            model_name='project',
            name='Digital_strategy',
            field=models.TextField(blank=True, db_column='Digital_strategy', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Digitalization',
            field=models.BooleanField(blank=True, db_column='Digitalization', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='P_budget',
            field=models.DecimalField(blank=True, db_column='P_budget', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='P_budgeted',
            field=models.BooleanField(blank=True, db_column='P_budgeted', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='P_description',
            field=models.TextField(blank=True, db_column='P_description', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='P_end_date',
            field=models.DateField(blank=True, db_column='P_end_date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='P_start_date',
            field=models.DateField(blank=True, db_column='P_start_date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Progress',
            field=models.IntegerField(blank=True, db_column='Progress', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Requestor',
            field=models.CharField(blank=True, db_column='Requestor', max_length=255, null=True),
        ),
    ]
